[project]
name = "tts-dataset-expander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=2.3.2",
    "pydub>=0.25.1",
]
